### ISSUE TITLE
Font color for code blocks

### ISSUE THREAD

**Issue by aso595** [home-assistant-community-themes/midnight#16]
Looking at the appdaemon documentation within Home Assistant, any code snippets are unreadable. They appear as white text on white text.

To reproduce, within Home Assistant.

1. Supervisor > Install AppDaemon 4
1. Under AppDaemon, click on 'Documentation' at the top.

Setting the code background color to the same as the sidebar fixes the problem. I added this to end of the `.yaml` file:

`  markdown-code-background-color: "var(--paper-listbox-background-color)"`

I've noticed the same thing happens with several other dark themes. A couple of examples I've seen this happening on are midnight_blue and material_dark_red.

**Comment by pho3nixf1re** [comment]
If you want to create a PR I would love to review it and merge it right away. I've noticed this problem myself.

**Comment by pho3nixf1re** [comment]
Resolved and merged in #17
