### ISSUE TITLE
Zone descriptions on the map are white

### ISSUE THREAD

**Issue by Santobert** [home-assistant-community-themes/midnight#2]
The names of the zones are white on the map, which made them unreadable.
Reopening: https://github.com/pho3nixf1re/home-assistant-theme-midnight/issues/2

**Comment by pho3nixf1re** [comment]
From what I can tell this may not be fixable as the map card is currently designed. As a work-around you can set the map card to `dark_mode: true` then the light icons will be visible on the dark map. I'm not familiar with the map card internals be we might be able to supply it an override for 'dark' themes so the icons can display on light embedded maps. Essentially the colors would need to swap.

**Comment by Santobert** [comment]
I was referring to the map section. Not the map card. I'm not sure if it's possible to put the map into dark mode.....

![grafik](https://user-images.githubusercontent.com/15657682/66731755-329a8c00-ee59-11e9-9da0-12b50955aabf.png)

**Comment by maartenpaauw** [comment]
https://community.home-assistant.io/t/how-to-change-map-icon/59218

**Comment by maartenpaauw** [comment]
I'll close this issue for now.
