### ISSUE TITLE
Border of Cards

### ISSUE THREAD

**Issue by 03397** [home-assistant-community-themes/midnight#20]
After the recent changes in version 0.113.0 the border lines of the cards are barely visible.
![image](https://user-images.githubusercontent.com/6150853/88365655-6fec5c80-cd8f-11ea-9644-79cebc4f1b8d.png)

**Comment by pho3nixf1re** [comment]
This is actually related to an existing issue. I just opened #21 which resolves this issue. Closing as a duplicate of #18
