### ISSUE TITLE
Shutter level percentage not shown

### ISSUE THREAD

**Issue by degrashopper** [home-assistant-community-themes/midnight#43]
When you change the shutter level the percentage in de scroller is not shown.
See attachement. left is midnight theme right is HA dark theme.
![percentage](https://github.com/home-assistant-community-themes/midnight/assets/8464491/bc4b2233-1742-419d-a478-a0a6510a185e)

**Comment by bratanon** [comment]
Same with light dimming level. Guess its the same for all "sliders"

**Comment by bratanon** [comment]
I have created a PR to fix this.

**Comment by pho3nixf1re** [comment]
I approved the pr, waiting for build to finish and as long as it clears I'll merge right away.
