### ISSUE TITLE
Buttons inside cards are not themed at all and look bad

### ISSUE THREAD

**Issue by arigit** [home-assistant-community-themes/midnight#9]
Cards can now include on/off type buttons, like for example the simple-thermostat card:

![image](https://user-images.githubusercontent.com/652673/68533193-24724b00-02f3-11ea-97b1-b952942937db.png)

(card: https://github.com/nervetattoo/simple-thermostat)

They look awful with the midnight theme.

Basically the button on/off state is not being themed at all. Here's the default HA theme showing the same colors for the buttons:

![image](https://user-images.githubusercontent.com/652673/68533205-4c61ae80-02f3-11ea-9fbd-5fe2a70a4201.png)

**Comment by maartenpaauw** [comment]
Thanks for reporting :)

**Comment by maartenpaauw** [comment]
#15 will fix this.

**Comment by pho3nixf1re** [comment]
Closing as resolved now that #15 is merged. Thanks!
